services:
    kafka:
        image: docker.io/bitnamilegacy/kafka:3.3.2
        container_name: kafka
        ports:
            - "9092:9092" # internal docker network
            - "9094:9094" # external --  echo '{"id":"1"}' | kcat -Pb :9094 -t test -p 0
        environment:
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_NODE_ID=0
            - KAFKA_CFG_PROCESS_ROLES=controller,broker
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093

        volumes:
          - kafka_data:/var/lib/kafka/data
        healthcheck:
            interval: 10s
            retries: 30
            start_period: 10s
            test:
                [
                    "CMD-SHELL",
                    "kafka-topics.sh --bootstrap-server :9092 --topic hc --create --if-not-exists && kafka-topics.sh --bootstrap-server :9092 --topic hc --describe",
                ]
            timeout: 5s
        restart: on-failure
volumes:
  kafka_data: